server:
  tomcat:
    accept-count: 1000
    max-connections: 1200
    max-threads: 1000

########## ORM ##########
mybatis:
  mapper-locations:
  - classpath:com.ydt.bespoke.**.mapper/*.xml
  type-aliases-package: com.ydt.bespokepoke.**.pojo.po
  configuration:
    map-underscore-to-camel-case: true

########## 通用Mapper ##########
mapper:
  identity: MYSQL
  mappers:
  - com.ydt.framework.mybatis.mapper.BaseMapper
  not-empty: false

########## 分页插件 ##########
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true

########## swagger ##########
swagger:
  enabled: true
  docket:
    basic:
      base-package: com.ydt.bespoke.basic
    balance:
      base-package: com.ydt.bespoke.balance
    fittingroom:
      base-package: com.ydt.bespoke.fittingroom
    product:
      base-package: com.ydt.bespoke.product
    sales:
      base-package: com.ydt.bespoke.sales
    sms:
      base-package: com.ydt.bespoke.sms
    staff:
      base-package: com.ydt.bespoke.staff
    returns:
      base-package: com.ydt.bespoke.returns