########## 数据库 ##########
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fox-demo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    password: root
    username: root