############ Mybatis ###########
mybatis:
    type-aliases-package: com.fun.fox.**.model
    mapper-locations: classpath:com.fun.fox.**.mapper/*Mapper.xml
########## 通用Mapper ##########
mapper:
  mappers:
      - com.sun.fox.mybatis.base.bmapper.BaseDaoMapper
  not-empty: false
  identity: MYSQL

    ########## 分页插件 ##########
pagehelper:
      helper-dialect: mysql
      params: count=countSql
      reasonable: true
      support-methods-arguments: true
