########## 数据库 ##########
#druid:
#    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
#    username: root
#    password: root
#    initial-size: 1
#    min-idle: 1
#    max-active: 20
#    test-on-borrow: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    password: root
    username: root
############ Mybatis ###########
mybatis:
    type-aliases-package: com.fun.fox.**.model
    mapper-locations: classpath:com.fun.fox.**.mapper/*Mapper.xml

########## 通用Mapper ##########
mapper:
  mappers:
      - com.sun.fox.mybatis.base.bmapper.BaseDaoMapper
  not-empty: false
  identity: MYSQL

########## 分页插件 ##########
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true
