security:
   oauth2:
      resource:
          token-info-uri: http://localhost:9098/oauth/check_token
      client:
          client-id: clientId
          client-secret: secretId
          user-authorization-uri: http://localhost:9098/oauth/authorize
          access-token-uri: http://localhost:9098/oauth/token
          grant-type: client_credentials

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG