security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      access-token-uri: http://localhost:9098/oauth/token
      user-authorization-uri: http://localhost:9098/oauth/authorize
    resource:
      user-info-uri: http://localhost:9098/

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG