########## 数据库 ##########
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    password: root
    username: root

############ Mybatis ###########
mybatis:
    type-aliases-package: com.fun.fox.**.mapper.mo
    mapper-locations:
        - classpath: com.fun.fox.**.mapper/*.xml
mapper:
    mappers:
        - com.sun.fox.mybatis.base.mapper.BaseDaoMapper
    not-empty: false
    identity: MYSQL

