########## 数据库 ##########
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crm_dev?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    password: root
    username: root


