server:
  port: 8761                    # 指定该Eureka实例的端口
spring:
    application:
      name: sunfox-Eureka
    profiles:
      active: dev
logging:
  file: logs/sunfox-discovery.log
  pattern:
    console: '[ %-5level] [%date{yyyy-MM-dd HH:mm:ss}] %logger{96} [%line] - %msg%n'
    file: '[ %-5level] [%date{yyyy-MM-dd HH:mm:ss}] %logger{96} [%line] - %msg%n'
---
spring:
  profiles: dev
  cloud:
    inetutils:
      ignored-interfaces:
        - docker0
        - veth.*
      preferred-networks:
        - 192.168
        - 10.0.0.0
eureka:
  instance:
    hostname: localhost         # 指定该Eureka实例的主机名
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# 参考文档：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#_standalone_mode
# 参考文档：http://my.oschina.net/buwei/blog/618756


